version: "3"
services:
    DB:
        image: postgres:latest
        volumes:
            - /data:/data/db
        container_name: ExamApp
        env_file: .env
        networks:
            - shared
        ports:
            -   5432:5432
    api:
        ports:
            -  46258:46258
        build:
            dockerfile: Dockerfile
            context: .
        env_file:
            - src/main/resources/backend.env
        networks:
            - shared
            - public

networks:
    shared:
        internal: true
    public:
        driver: bridge