version: "3"
name: "examapp-db"
services:
    DB:
        image: postgres:latest
        volumes: 
            - /data:/data/db
        ports:
            - "5432:5432"
        container_name: ExamApp
        env_file: .env